{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Heads Up Mobile iOS SDK provides a structured, easy-to-use API for accessing the Heads Up Cloud platform. It contains a set of high level objects you can use to perform a variety of tasks, such as:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Log in or register with Heads Up’s cloud services using Single Sign On (SSO) or user id and password"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Connect and disconnect user’s devices such as Oura, Dexcom, Fitbit, and so on"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Retrieve health metric data from the Heads Up cloud for optional storage in a data lakehouse"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Upload Apple HealthKit data to the cloud in both foreground and background modes"},{"type":"text","text":" "},{"type":"image","identifier":"headsuplogo.png"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"headsup_mobile_sdk","title":"headsup_mobile_sdk","symbolKind":"module","role":"collection","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"]},{"title":"Business Controllers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Graph","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MessagingConversationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PhotoJournalConversationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit"]},{"title":"Business Models","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"]},{"title":"Metric Base Classes","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthMetric","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/NutritionHealthMetric"]},{"title":"Metrics","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BasalTemperature","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BloodGlucose","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BloodPressure","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BodyFat","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BodyMassIndex","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BodyTemperature","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/CaloriesBurned","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/CaloriesConsumed","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryCarbohydrates","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryFatTotal","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryFatMonounsaturated","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryPolyunsaturatedFat","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryProtein","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietarySaturatedFat","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryWater","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HeartRate","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HeartRateVariability","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MeditationTime","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/OxygenSaturation","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RestingHeartRate","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Sleep","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Steps","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Temperature","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/VO2Max","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WaistCircumference","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Weight"]},{"title":"Articles","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesAppleHealth","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesHumanAPI","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIDPassword","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIntegrationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesOAuth","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingFlutter","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoggedInCheck","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserIDPassword","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserSSO","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LogoutUser","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserIDPassword","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserSSO"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BusinessController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientRecipientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DisplayType","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HKMeasurementConversion","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HUHClient","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HumanApiEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LS","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceIntegerValueOptions","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceStringValueOptions","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/OAuthEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PostResponseEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RecipientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ResponseEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SelectableItem","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingDisplayType","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserRegistrationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserSetting"]},{"title":"Protocols","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerDelegate","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKitUploadProgressDelegate"]},{"title":"Structures","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceField","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UncertainValue","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserCredentialsOAuthEntity"]},{"title":"Enumerations","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/CalendarRange","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationFilter","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationOrderBy","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/OrderDirection","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ServerName"]}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BloodPressure":{"role":"symbol","title":"BloodPressure","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BloodPressure"}],"abstract":[{"type":"text","text":"Blood Pressure Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BloodPressure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BloodPressure"}],"url":"\/documentation\/headsup_mobile_sdk\/bloodpressure"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationEntity":{"role":"symbol","title":"IntegrationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationEntity"}],"abstract":[{"type":"text","text":"Integration Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HumanApiEntity":{"role":"symbol","title":"HumanApiEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HumanApiEntity"}],"abstract":[{"type":"text","text":"HumanAPI entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HumanApiEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HumanApiEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/humanapientity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit":{"role":"symbol","title":"HealthKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"}],"abstract":[{"type":"text","text":"The primary HealthKit class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HealthKit"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LogoutUser":{"role":"article","title":"Log a User Out","abstract":[{"type":"text","text":"Regardless of whether a user has logged in with an id and password or via SSO, you use the same technique to log them out"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LogoutUser","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/logoutuser"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MeditationTime":{"role":"symbol","title":"MeditationTime","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeditationTime"}],"abstract":[{"type":"text","text":"Meditation Time Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MeditationTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MeditationTime"}],"url":"\/documentation\/headsup_mobile_sdk\/meditationtime"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RestingHeartRate":{"role":"symbol","title":"RestingHeartRate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestingHeartRate"}],"abstract":[{"type":"text","text":"Resting Heart Rate Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RestingHeartRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RestingHeartRate"}],"url":"\/documentation\/headsup_mobile_sdk\/restingheartrate"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity":{"role":"symbol","title":"SourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceEntity"}],"abstract":[{"type":"text","text":"Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/sourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegisterUserIDPassword":{"role":"article","title":"Register a User with User ID and Password","abstract":[{"type":"text","text":"This topic shows you how to register a user with Heads Up cloud services using a User ID and password."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserIDPassword","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registeruseridpassword"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSourcesIDPassword":{"role":"article","title":"Connecting and Disconnecting Sources with an ID and Password","abstract":[{"type":"text","text":"This topic shows you how to connect and disconnect integration sources with an ID and password."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIDPassword","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsourcesidpassword"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BodyTemperature":{"role":"symbol","title":"BodyTemperature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BodyTemperature"}],"abstract":[{"type":"text","text":"Body Mass Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BodyTemperature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BodyTemperature"}],"url":"\/documentation\/headsup_mobile_sdk\/bodytemperature"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/OxygenSaturation":{"role":"symbol","title":"OxygenSaturation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OxygenSaturation"}],"abstract":[{"type":"text","text":"Oxygen Saturation Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/OxygenSaturation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OxygenSaturation"}],"url":"\/documentation\/headsup_mobile_sdk\/oxygensaturation"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithUserData":{"role":"article","title":"Working With User Data","abstract":[{"type":"text","text":"Most of the functionality in the Heads Up Mobile SDK requires access to a user’s data. This topic discusses how to retrieve and update user data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithuserdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BasalTemperature":{"role":"symbol","title":"BasalTemperature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasalTemperature"}],"abstract":[{"type":"text","text":"Basal Temperature Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BasalTemperature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BasalTemperature"}],"url":"\/documentation\/headsup_mobile_sdk\/basaltemperature"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LS":{"role":"symbol","title":"LS","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LS"}],"abstract":[{"type":"text","text":"Localized Strings class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LS"}],"url":"\/documentation\/headsup_mobile_sdk\/ls"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UncertainValue":{"role":"symbol","title":"UncertainValue","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UncertainValue"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UncertainValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UncertainValue"}],"url":"\/documentation\/headsup_mobile_sdk\/uncertainvalue"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingController":{"role":"symbol","title":"TileSettingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingController"}],"abstract":[{"type":"text","text":"Tile Setting Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingController"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSourcesOAuth":{"role":"article","title":"Connecting and Disconnecting Sources with oAuth","abstract":[{"type":"text","text":"This topic shows you how to connect and disconnect integration sources using oAuth."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesOAuth","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsourcesoauth"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/CaloriesBurned":{"role":"symbol","title":"CaloriesBurned","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaloriesBurned"}],"abstract":[{"type":"text","text":"Calories burned Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/CaloriesBurned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CaloriesBurned"}],"url":"\/documentation\/headsup_mobile_sdk\/caloriesburned"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DietaryFatTotal":{"role":"symbol","title":"DietaryFatTotal","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DietaryFatTotal"}],"abstract":[{"type":"text","text":"Dietary Fat Total Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryFatTotal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DietaryFatTotal"}],"url":"\/documentation\/headsup_mobile_sdk\/dietaryfattotal"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Graph":{"role":"symbol","title":"Graph","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Graph"}],"abstract":[{"type":"text","text":"Graph Business Controller"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Graph","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Graph"}],"url":"\/documentation\/headsup_mobile_sdk\/graph"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BodyMassIndex":{"role":"symbol","title":"BodyMassIndex","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BodyMassIndex"}],"abstract":[{"type":"text","text":"Body Mass Index Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BodyMassIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BodyMassIndex"}],"url":"\/documentation\/headsup_mobile_sdk\/bodymassindex"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DietaryProtein":{"role":"symbol","title":"DietaryProtein","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DietaryProtein"}],"abstract":[{"type":"text","text":"Dietary Protein Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryProtein","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DietaryProtein"}],"url":"\/documentation\/headsup_mobile_sdk\/dietaryprotein"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientRecipientEntity":{"role":"symbol","title":"ClientRecipientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientRecipientEntity"}],"abstract":[{"type":"text","text":"Client Recipient Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientRecipientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientRecipientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/clientrecipiententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BloodGlucose":{"role":"symbol","title":"BloodGlucose","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BloodGlucose"}],"abstract":[{"type":"text","text":"Blood Glucose Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BloodGlucose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BloodGlucose"}],"url":"\/documentation\/headsup_mobile_sdk\/bloodglucose"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HKMeasurementConversion":{"role":"symbol","title":"HKMeasurementConversion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKMeasurementConversion"}],"abstract":[{"type":"text","text":"HealthKit Measurement conversion class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HKMeasurementConversion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKMeasurementConversion"}],"url":"\/documentation\/headsup_mobile_sdk\/hkmeasurementconversion"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LoginUserSSO":{"role":"article","title":"Log In with Single Sign On (SSO)","abstract":[{"type":"text","text":"This topic shows you how to log a user into the Heads Up Cloud Services using SSO."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserSSO","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/loginusersso"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegistrationLogin":{"role":"article","title":"Registration, Login and Logout","abstract":[{"type":"text","text":"After installing the Heads Up SDK, the next step in using the SDK’s features is to register and-or log in a user."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registrationlogin"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HUHClient":{"role":"symbol","title":"HUHClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUHClient"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HUHClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HUHClient"}],"url":"\/documentation\/headsup_mobile_sdk\/huhclient"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SelectableItem":{"role":"symbol","title":"SelectableItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectableItem"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SelectableItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectableItem"}],"url":"\/documentation\/headsup_mobile_sdk\/selectableitem"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController":{"role":"symbol","title":"UserController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserController"}],"abstract":[{"type":"text","text":"User Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserController"}],"url":"\/documentation\/headsup_mobile_sdk\/usercontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BodyFat":{"role":"symbol","title":"BodyFat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BodyFat"}],"abstract":[{"type":"text","text":"Body Fat Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BodyFat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BodyFat"}],"url":"\/documentation\/headsup_mobile_sdk\/bodyfat"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientController":{"role":"symbol","title":"ClientController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientController"}],"abstract":[{"type":"text","text":"Client Business Controller - Single accessed via the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientController"}],"url":"\/documentation\/headsup_mobile_sdk\/clientcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingFlutter":{"role":"article","title":"Integrating the Heads Up SDK in a Flutter Project","abstract":[{"type":"text","text":"This topic contains instructions on integrating the Heads Up Mobile SDK in a Flutter project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingFlutter","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingflutter"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationConfigController":{"role":"symbol","title":"IntegrationConfigController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationConfigController"}],"abstract":[{"type":"text","text":"Integration Config Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationConfigController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationconfigcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceStringValueOptions":{"role":"symbol","title":"ManualSourceStringValueOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceStringValueOptions"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceStringValueOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceStringValueOptions"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourcestringvalueoptions"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKitUploadProgressDelegate":{"role":"symbol","title":"HealthKitUploadProgressDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKitUploadProgressDelegate"}],"abstract":[{"type":"text","text":"HealthKit Upload Progress Delegate"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKitUploadProgressDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HealthKitUploadProgressDelegate"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkituploadprogressdelegate"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController":{"role":"symbol","title":"IntegrationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationController"}],"abstract":[{"type":"text","text":"\/\/\/ Integration Business Controller - API for Heads Up integration sources such as  Oura, Dexcom, Fitbit, etc."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationConfigEntity":{"role":"symbol","title":"IntegrationConfigEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationConfigEntity"}],"abstract":[{"type":"text","text":"Integration Config Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationConfigEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationconfigentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DietaryPolyunsaturatedFat":{"role":"symbol","title":"DietaryPolyunsaturatedFat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DietaryPolyunsaturatedFat"}],"abstract":[{"type":"text","text":"Dietary Polyunsaturated Fat Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryPolyunsaturatedFat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DietaryPolyunsaturatedFat"}],"url":"\/documentation\/headsup_mobile_sdk\/dietarypolyunsaturatedfat"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Temperature":{"role":"symbol","title":"Temperature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Temperature"}],"abstract":[{"type":"text","text":"Temperature business controller"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Temperature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Temperature"}],"url":"\/documentation\/headsup_mobile_sdk\/temperature"},"headsuplogo.png":{"alt":"HeadsUp Logo","type":"image","identifier":"headsuplogo.png","variants":[{"url":"\/images\/headsuplogo.png","traits":["1x","light"]}]},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LoggedInCheck":{"role":"article","title":"Check if a User is Logged In","abstract":[{"type":"text","text":"When your app first starts up, you should normally check if a user is already logged in, and if not, present them with UI to do so."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoggedInCheck","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/loggedincheck"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSourcesIntegrationController":{"role":"article","title":"Getting a List of Integration Sources with the IntegrationController","abstract":[{"type":"text","text":"This topic shows you how to retrieve a list of integration sources using the IntegrationController class."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIntegrationController","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsourcesintegrationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ResponseEntity":{"role":"symbol","title":"ResponseEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseEntity"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ResponseEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/responseentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BusinessController":{"role":"symbol","title":"BusinessController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessController"}],"abstract":[{"type":"text","text":"Base Class of all Business Controllers"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BusinessController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessController"}],"url":"\/documentation\/headsup_mobile_sdk\/businesscontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DisplayType":{"role":"symbol","title":"DisplayType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DisplayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayType"}],"url":"\/documentation\/headsup_mobile_sdk\/displaytype"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/NutritionHealthMetric":{"role":"symbol","title":"NutritionHealthMetric","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NutritionHealthMetric"}],"abstract":[{"type":"text","text":"Nutrition Health Metric base class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/NutritionHealthMetric","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NutritionHealthMetric"}],"url":"\/documentation\/headsup_mobile_sdk\/nutritionhealthmetric"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceController":{"role":"symbol","title":"ManualSourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceController"}],"abstract":[{"type":"text","text":"Manual Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationOrderBy":{"role":"symbol","title":"ConversationOrderBy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationOrderBy"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationOrderBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationOrderBy"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationorderby"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Steps":{"role":"symbol","title":"Steps","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Steps"}],"abstract":[{"type":"text","text":"Steps Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Steps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Steps"}],"url":"\/documentation\/headsup_mobile_sdk\/steps"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/OrderDirection":{"role":"symbol","title":"OrderDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderDirection"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/OrderDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrderDirection"}],"url":"\/documentation\/headsup_mobile_sdk\/orderdirection"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RecipientEntity":{"role":"symbol","title":"RecipientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecipientEntity"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RecipientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecipientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/recipiententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerController":{"role":"symbol","title":"FastingTimerController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerController"}],"abstract":[{"type":"text","text":"Fasting Timer Business Controller - Singleton accessed via "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerController"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimercontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements":{"role":"symbol","title":"Entitlements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Entitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Entitlements"}],"url":"\/documentation\/headsup_mobile_sdk\/entitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserRegistrationEntity":{"role":"symbol","title":"UserRegistrationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserRegistrationEntity"}],"abstract":[{"type":"text","text":"User Registration Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserRegistrationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserRegistrationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userregistrationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LoginUserIDPassword":{"role":"article","title":"Log In with an ID and Password","abstract":[{"type":"text","text":"This topic shows you how to log a user into the Heads Up Cloud Services using an ID and password."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserIDPassword","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/loginuseridpassword"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WaistCircumference":{"role":"symbol","title":"WaistCircumference","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WaistCircumference"}],"abstract":[{"type":"text","text":"Waist circumference Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WaistCircumference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WaistCircumference"}],"url":"\/documentation\/headsup_mobile_sdk\/waistcircumference"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ArchitecturalOverview":{"role":"article","title":"Architectural Overview","abstract":[{"type":"text","text":"This article provides an architectural overview of how your app interacts with the Heads Up Mobile SDK to access the functionality of the Heads Up Cloud Platform."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/architecturaloverview"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Weight":{"role":"symbol","title":"Weight","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Weight"}],"abstract":[{"type":"text","text":"Body Weight Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Weight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Weight"}],"url":"\/documentation\/headsup_mobile_sdk\/weight"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DietaryCarbohydrates":{"role":"symbol","title":"DietaryCarbohydrates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DietaryCarbohydrates"}],"abstract":[{"type":"text","text":"Dietary Carbohydrates Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryCarbohydrates","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DietaryCarbohydrates"}],"url":"\/documentation\/headsup_mobile_sdk\/dietarycarbohydrates"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController":{"role":"symbol","title":"MetricController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricController"}],"abstract":[{"type":"text","text":"Metric Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricController"}],"url":"\/documentation\/headsup_mobile_sdk\/metriccontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingEntity":{"role":"symbol","title":"TileSettingEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingEntity"}],"abstract":[{"type":"text","text":"Tile Setting Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingSDK":{"role":"article","title":"Installing the Heads Up SDK","abstract":[{"type":"text","text":"This topic contains instructions for installing the Heads Up Mobile SDK and integrating it into your mobile project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingsdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/CaloriesConsumed":{"role":"symbol","title":"CaloriesConsumed","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaloriesConsumed"}],"abstract":[{"type":"text","text":"Calories Consumed Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/CaloriesConsumed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CaloriesConsumed"}],"url":"\/documentation\/headsup_mobile_sdk\/caloriesconsumed"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/headsup_mobile_sdkVersionString":{"role":"symbol","title":"headsup_mobile_sdkVersionString","fragments":[{"kind":"identifier","text":"headsup_mobile_sdkVersionString"}],"abstract":[{"type":"text","text":"Project version string for headsup_mobile_sdk."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/headsup_mobile_sdkVersionString","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/headsup_mobile_sdkversionstring"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationFilter":{"role":"symbol","title":"ConversationFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationFilter"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationFilter"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationfilter"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/headsup_mobile_sdkVersionNumber":{"role":"symbol","title":"headsup_mobile_sdkVersionNumber","fragments":[{"kind":"identifier","text":"headsup_mobile_sdkVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for headsup_mobile_sdk."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/headsup_mobile_sdkVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/headsup_mobile_sdkversionnumber"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSourcesHumanAPI":{"role":"article","title":"Connecting & Disconnecting Sources with Human API","abstract":[{"type":"text","text":"This topic shows you how to connect and disconnect integration sources with Human API."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesHumanAPI","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsourceshumanapi"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RetrievingHealthData":{"role":"collectionGroup","title":"Retrieving Health Data","abstract":[{"type":"text","text":"There us a wealth of data available in the Heads Up platform you can retrieve and manipulate from the Heads Up SDK. This article shows the objects you can use to download this data into your own app."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceEntity":{"role":"symbol","title":"ManualSourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceEntity"}],"abstract":[{"type":"text","text":"Manual Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity":{"role":"symbol","title":"ConversationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntity"}],"abstract":[{"type":"text","text":"Conversation Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Sleep":{"role":"symbol","title":"Sleep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sleep"}],"abstract":[{"type":"text","text":"Sleep Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Sleep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Sleep"}],"url":"\/documentation\/headsup_mobile_sdk\/sleep"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DietarySaturatedFat":{"role":"symbol","title":"DietarySaturatedFat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DietarySaturatedFat"}],"abstract":[{"type":"text","text":"Dietary Saturated Fat Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietarySaturatedFat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DietarySaturatedFat"}],"url":"\/documentation\/headsup_mobile_sdk\/dietarysaturatedfat"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricEntity":{"role":"symbol","title":"MetricEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricEntity"}],"abstract":[{"type":"text","text":"Metric Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/metricentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ServerName":{"role":"symbol","title":"ServerName","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServerName"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ServerName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServerName"}],"url":"\/documentation\/headsup_mobile_sdk\/servername"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DietaryFatMonounsaturated":{"role":"symbol","title":"DietaryFatMonounsaturated","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DietaryFatMonounsaturated"}],"abstract":[{"type":"text","text":"Dietaryy Monounsaturated Fat Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryFatMonounsaturated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DietaryFatMonounsaturated"}],"url":"\/documentation\/headsup_mobile_sdk\/dietaryfatmonounsaturated"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/PostResponseEntity":{"role":"symbol","title":"PostResponseEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostResponseEntity"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PostResponseEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PostResponseEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/postresponseentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HeartRateVariability":{"role":"symbol","title":"HeartRateVariability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeartRateVariability"}],"abstract":[{"type":"text","text":"Heart Rate Variability Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HeartRateVariability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeartRateVariability"}],"url":"\/documentation\/headsup_mobile_sdk\/heartratevariability"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerEntity":{"role":"symbol","title":"FastingTimerEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerEntity"}],"abstract":[{"type":"text","text":"Fasting Timer Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimerentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DietaryWater":{"role":"symbol","title":"DietaryWater","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DietaryWater"}],"abstract":[{"type":"text","text":"Dietary Water Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DietaryWater","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DietaryWater"}],"url":"\/documentation\/headsup_mobile_sdk\/dietarywater"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithAppleHealthKit":{"role":"collectionGroup","title":"Working With Apple HealthKit","abstract":[{"type":"text","text":"Apple’s HealthKit provides a vast array of health information that is accessible through the Heads Up SDK. In this article you’ll learn about the Heads Up SDK objects you can work with to upload and manipulate HealthKit data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthMetric":{"role":"symbol","title":"HealthMetric","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthMetric"}],"abstract":[{"type":"text","text":"Health Metric base class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthMetric","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HealthMetric"}],"url":"\/documentation\/headsup_mobile_sdk\/healthmetric"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DefaultEntitlements":{"role":"symbol","title":"DefaultEntitlements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultEntitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultEntitlements"}],"url":"\/documentation\/headsup_mobile_sdk\/defaultentitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationRecipientController":{"role":"symbol","title":"ConversationRecipientController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRecipientController"}],"abstract":[{"type":"text","text":"Conversation Recipient Business Controller - Singleton accessed via "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRecipientController"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationrecipientcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserCredentialsOAuthEntity":{"role":"symbol","title":"UserCredentialsOAuthEntity","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserCredentialsOAuthEntity"}],"abstract":[{"type":"text","text":"User Credentials OAuth Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserCredentialsOAuthEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserCredentialsOAuthEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/usercredentialsoauthentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegisterUserSSO":{"role":"article","title":"Register a User with Single Sign On (SSO)","abstract":[{"type":"text","text":"This topic shows you how to register a user with Heads Up Cloud Services using Single Sign On"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserSSO","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registerusersso"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationRecipientEntity":{"role":"symbol","title":"ConversationRecipientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRecipientEntity"}],"abstract":[{"type":"text","text":"Conversation Recipient Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRecipientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationrecipiententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSourcesAppleHealth":{"role":"article","title":"Connecting and Disconnecting Apple Health","abstract":[{"type":"text","text":"This topic shows you how to connect and disconnect Apple Health."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesAppleHealth","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsourcesapplehealth"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingDisplayType":{"role":"symbol","title":"TileSettingDisplayType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingDisplayType"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingDisplayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingDisplayType"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingdisplaytype"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSources":{"role":"article","title":"Connecting and Disconnecting Sources","abstract":[{"type":"text","text":"The Heads Up platform integrates with many popular apps and data sources such as Apple Health, Oura, Dexcom and Fitbit. In this article, you’ll learn how to connect and disconnect these various sources."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsources"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/OAuthEntity":{"role":"symbol","title":"OAuthEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthEntity"}],"abstract":[{"type":"text","text":"OAuth Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/OAuthEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuthEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/oauthentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity":{"role":"symbol","title":"UserEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"abstract":[{"type":"text","text":"User Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceIntegerValueOptions":{"role":"symbol","title":"ManualSourceIntegerValueOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceIntegerValueOptions"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceIntegerValueOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceIntegerValueOptions"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourceintegervalueoptions"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/CalendarRange":{"role":"symbol","title":"CalendarRange","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalendarRange"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/CalendarRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CalendarRange"}],"url":"\/documentation\/headsup_mobile_sdk\/calendarrange"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientEntity":{"role":"symbol","title":"ClientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientEntity"}],"abstract":[{"type":"text","text":"Client Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/cliententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MessagingConversationController":{"role":"symbol","title":"MessagingConversationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingConversationController"}],"abstract":[{"type":"text","text":"Photo Journal Conversation Business Controller - Singleton accessed via the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MessagingConversationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingConversationController"}],"url":"\/documentation\/headsup_mobile_sdk\/messagingconversationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceField":{"role":"symbol","title":"ManualSourceField","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceField"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceField"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourcefield"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientListEntity":{"role":"symbol","title":"ClientListEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientListEntity"}],"abstract":[{"type":"text","text":"Client List Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientListEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/clientlistentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerDelegate":{"role":"symbol","title":"FastingTimerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerDelegate"}],"abstract":[{"type":"text","text":"Fasting Timer Delegate protocol"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerDelegate"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimerdelegate"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceController":{"role":"symbol","title":"SourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceController"}],"abstract":[{"type":"text","text":"Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/sourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HeartRate":{"role":"symbol","title":"HeartRate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeartRate"}],"abstract":[{"type":"text","text":"Heart Rate Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HeartRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HeartRate"}],"url":"\/documentation\/headsup_mobile_sdk\/heartrate"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/PhotoJournalConversationController":{"role":"symbol","title":"PhotoJournalConversationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoJournalConversationController"}],"abstract":[{"type":"text","text":"Photo Journal Conversation Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PhotoJournalConversationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhotoJournalConversationController"}],"url":"\/documentation\/headsup_mobile_sdk\/photojournalconversationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/VO2Max":{"role":"symbol","title":"VO2Max","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VO2Max"}],"abstract":[{"type":"text","text":"VO2 Max Metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/VO2Max","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VO2Max"}],"url":"\/documentation\/headsup_mobile_sdk\/vo2max"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserSetting":{"role":"symbol","title":"UserSetting","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserSetting"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserSetting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserSetting"}],"url":"\/documentation\/headsup_mobile_sdk\/usersetting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"]},{"title":"Business Controllers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit"]},{"title":"Business Models","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"]},{"title":"Articles","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesAppleHealth","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesHumanAPI","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIDPassword","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIntegrationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesOAuth","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingFlutter","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoggedInCheck","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserIDPassword","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserSSO","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LogoutUser","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserIDPassword","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserSSO"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HUHClient","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserSetting"]},{"title":"Variables","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/headsup_mobile_sdkVersionNumber","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/headsup_mobile_sdkVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/title","value":"HealthKit"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/fragments","value":[{"kind":"identifier","text":"HealthKit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HUHClient\/title","value":"HUHClient"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HUHClient\/fragments","value":[{"kind":"identifier","text":"HUHClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/title","value":"Entitlements"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/fragments","value":[{"kind":"identifier","text":"Entitlements"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/title","value":"MetricEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/fragments","value":[{"kind":"identifier","text":"MetricEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1DefaultEntitlements\/title","value":"DefaultEntitlements"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1DefaultEntitlements\/fragments","value":[{"kind":"identifier","text":"DefaultEntitlements"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/title","value":"UserEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserSetting\/title","value":"UserSetting"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserSetting\/fragments","value":[{"kind":"identifier","text":"UserSetting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}