{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The primary classes you’ll use when working with sources are the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity"},{"type":"text","text":" classes. The list of sources can change based on the permissions of the user that is currently logged in, so you need a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"},{"type":"text","text":" object to use in conjunction with the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to instantiate an instance of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController"},{"type":"text","text":" class, passing a reference to a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["if let userInfo = UserController.userEntity {","","    let integrationController = IntegrationController(userInfo: userInfo)","    ","    \/\/ Now you can work with the IntegrationController object","    integrationController?.getIntegrations(completion: { ","        entityList, errorMessage in","        ","    })","}"]},{"anchor":"Retrieving-a-List-of-Sources-for-a-User","level":3,"type":"heading","text":"Retrieving a List of Sources for a User"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use the "},{"type":"strong","inlineContent":[{"type":"text","text":"IntegrationController.getIntegrations()"}]},{"type":"text","text":" method to retrieve a valid list of integrations for a user."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController\/getIntegrations(completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["integrationController?.getIntegrations(completion: { entityList, errorMessage in","    ","    if let integrationList = entityList {","        self.integrationList = integrationList","    }","    self.refreshSources()","})"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method returns a list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity"},{"type":"text","text":" objects that have the following properties:"}]},{"type":"codeListing","syntax":"swift","code":["public class IntegrationEntity: Decodable {","    \/\/\/ Url, or unique name of the integration source","    public var url: String","    \/\/\/ Authorization type (\"oauth\", \"password\", \"hapi\", \"upload\"","    public var auth_type: StringLiteralType","    \/\/\/ Display name of the integration source","    public var name: String","    \/\/\/ True if the source is already connected, otherwise false","    public var connected: Bool","    \/\/\/ The display position of the integration in a list","    public var position: Int?","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"NOTE: The "},{"type":"strong","inlineContent":[{"type":"text","text":"auth_type"}]},{"type":"text","text":" property lets you know which method on the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController"},{"type":"text","text":" you need to call to connect and disconnect each integration source."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/connectingsourcesintegrationcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/connectingsourcesintegrationcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIntegrationController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This topic shows you how to retrieve a list of integration sources using the IntegrationController class."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting a List of Integration Sources with the IntegrationController","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity":{"role":"symbol","title":"UserEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"abstract":[{"type":"text","text":"User Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController":{"role":"symbol","title":"IntegrationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationController"}],"abstract":[{"type":"text","text":"\/\/\/ Integration Business Controller - API for Heads Up integration sources such as  Oura, Dexcom, Fitbit, etc."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationEntity":{"role":"symbol","title":"IntegrationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationEntity"}],"abstract":[{"type":"text","text":"Integration Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController/getIntegrations(completion:)":{"role":"symbol","title":"getIntegrations(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getIntegrations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entityList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:18headsup_mobile_sdk21IntegrationControllerC1Txmfp"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets all valid integrations, filtering out integrations not allowed in entitlements"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController\/getIntegrations(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller\/getintegrations(completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/title","value":"UserEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}