{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"FitBit, myfitnesspal, Google Fit and iHealth use Human API to connect and disconnect."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The primary classes you’ll use when connecting and disconnecting a Human API source are the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController"},{"type":"text","text":" and its associated "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity"},{"type":"text","text":" class."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" Before reading this topic, make sure you have read the information on retrieving a list of integration sources, in the main topic "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIntegrationController"},{"type":"text","text":"."}]},{"anchor":"Connecting-Sources-with-Human-API","level":3,"type":"heading","text":"Connecting Sources with Human API"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When an IntegrationEntity’s "},{"type":"strong","inlineContent":[{"type":"text","text":"auth_type"}]},{"type":"text","text":" property is set to “hapi”, you need to use the "},{"type":"strong","inlineContent":[{"type":"text","text":"IntegrationController.connectHumanApiIntegration()"}]},{"type":"text","text":" method to connect it."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController\/connectHumanApiIntegration(clientId:humanId:sessionToken:completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When connecting a Human API source, there are some important data you need."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Human API Source ID"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here are the Human API Source Id’s you need for each source"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"fitbit - “54dc427aaa6b4cb7d6202f01”,"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"myfitnesspal - “54dc427aaa6b4cb7d6202f10”,"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"googlefit - “55dcac1ba2a64df204e3d5a0”,"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ihealth - “54dc427aaa6b4cb7d6202f03”"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Human API External Id"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each user has a Human API Id assigned to them which you need to use when connecting any of the Human API sources. This Id can be found in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"},{"type":"text","text":" object’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/humanExternalId"},{"type":"text","text":" property."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Human Client Id"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each company working with Human API is assigned their own client id. You will need to obtain a client id from Human API in order to connect your app to Human API sources."}]},{"anchor":"Connecting-a-Human-API-Source","level":3,"type":"heading","text":"Connecting a Human API Source"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are five main steps in connecting an Human API source:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Get the Human API Client ID"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Get a UserEntity object"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Build an authentication URL using the IntegrationController object’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController\/buildHumanApiAuthUrl(sourceURL:userEntity:)"},{"type":"text","text":" method"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Initialize an ASWebAuthenticationSession with code that will call the IntegrationController’s connectHumanAPIIntegration() method"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Start the ASWebAuthenticationSession session"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["","\/\/ 1. Get the Human API Client ID","if let clientId = self.getHumanAPIClientID() {","","    \/\/ 2. Get a UserEntity object","    if let userEntity = UserController.userEntity {","","        \/\/ 3. Build an authentication URL","        if let authURL = self.integrationController?.buildHumanApiAuthUrl(sourceURL: \"fitbit\", userEntity: userEntity) {","                ","            \/\/ 4. Initialize an ASWebAuthentication session with code that will call ","            \/\/    the IntegrationController's connectHumanAPIIntegration() method","            self.session = ASWebAuthenticationSession(url: authURL, callbackURLScheme: \"headsuphealth\")","            { callbackURL, error in","               ","                \/\/ 1","                guard","                  error == nil,","                  let callbackURL = callbackURL,","                  \/\/ 2","                  let queryItems = URLComponents(string: callbackURL.absoluteString)?.queryItems,","                  \/\/ 3","                  let sessionToken = queryItems.first(where: { $0.name == \"sessionToken\" })?.value,","                    let humanId = queryItems.first(where: { $0.name == \"humanId\" })?.value","                else {","                  \/\/ 5","                  print(\"An error occurred when attempting to sign in.\")","                  return","                }","                ","                \/\/ Call the IntegrationController's connectHumanAPIIntegration() method","                self.integrationController?.connectHumanApiIntegration(clientId: clientId, humanId: humanId, sessionToken: sessionToken, completion: { entity, errorMessage in","                    ","                    if entity != nil {","                        \/\/ Need to refresh the user info","                        UserController.shared.getUserInfo { entity, errorMessage in","                        }","                        self.displaySuccessfulConnection(source: source, sourceName: sourceName)","                    }","                    else {","                        let alertMessage = UIAlertController(title: \"Connection Error\", message: errorMessage, preferredStyle: .alert)","                        let okAction = UIAlertAction(title: \"OK\", style: .default, handler: { (action) -> Void in","                             })","                        alertMessage.addAction(okAction)","                            ","                        self.present(alertMessage, animated: true, completion: nil)","                    }","                })","            }","            ","            \/\/ 5. Start the ASWebAuthenticationSession session","            self.session?.presentationContextProvider = self","            self.session?.start()","        }","    }","}"]},{"anchor":"Disconnecting-a-Human-API-Source","level":3,"type":"heading","text":"Disconnecting a Human API Source"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To disconnect a Human API source, just pass the url of the source integration to be disconnected"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["self.integrationController?.disconnectHumanApiIntegration(url: \"fitbit\", completion: { ","    success, errorMessage in","    ","    \/\/ Let the user know if the connection succeeded or failed","})"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/connectingsourceshumanapi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/connectingsourceshumanapi"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesHumanAPI","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This topic shows you how to connect and disconnect integration sources with Human API."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Connecting & Disconnecting Sources with Human API","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController":{"role":"symbol","title":"IntegrationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationController"}],"abstract":[{"type":"text","text":"\/\/\/ Integration Business Controller - API for Heads Up integration sources such as  Oura, Dexcom, Fitbit, etc."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController/connectHumanApiIntegration(clientId:humanId:sessionToken:completion:)":{"role":"symbol","title":"connectHumanApiIntegration(clientId:humanId:sessionToken:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectHumanApiIntegration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"humanId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HumanApiEntity","preciseIdentifier":"s:18headsup_mobile_sdk14HumanApiEntityC"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Connects the Human API Integration"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController\/connectHumanApiIntegration(clientId:humanId:sessionToken:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller\/connecthumanapiintegration(clientid:humanid:sessiontoken:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSourcesIntegrationController":{"role":"article","title":"Getting a List of Integration Sources with the IntegrationController","abstract":[{"type":"text","text":"This topic shows you how to retrieve a list of integration sources using the IntegrationController class."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSourcesIntegrationController","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsourcesintegrationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationEntity":{"role":"symbol","title":"IntegrationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationEntity"}],"abstract":[{"type":"text","text":"Integration Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity":{"role":"symbol","title":"UserEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"abstract":[{"type":"text","text":"User Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController/buildHumanApiAuthUrl(sourceURL:userEntity:)":{"role":"symbol","title":"buildHumanApiAuthUrl(sourceURL:userEntity:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHumanApiAuthUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sourceURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userEntity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserEntity","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)UserEntity"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController\/buildHumanApiAuthUrl(sourceURL:userEntity:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller\/buildhumanapiauthurl(sourceurl:userentity:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/humanExternalId":{"role":"symbol","title":"humanExternalId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"humanExternalId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Human API external id"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/humanExternalId","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/humanexternalid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/title","value":"UserEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}