{"seeAlsoSections":[{"title":"Business Models","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntity"}],"title":"ConversationEntity","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:18headsup_mobile_sdk18ConversationEntityC","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEntity"}]},"abstract":[{"type":"text","text":"Conversation Entity"}],"sections":[],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/attachment","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/body","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/createdAt","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/dislikes","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/hasAttachment","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/id","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/isArchived","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/isRead","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/likes","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/mailboxType","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/messageCount","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/messageType","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/postedAt","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/recipients","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/responses","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/senderName","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/senderUuid","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/subject","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/tags","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/updatedAt"]}],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/conversationentity"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntity"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/init(from:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/messageType":{"role":"symbol","title":"messageType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/messageType","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/messagetype"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/mailboxType":{"role":"symbol","title":"mailboxType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mailboxType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/mailboxType","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/mailboxtype"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/senderName":{"role":"symbol","title":"senderName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"senderName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/senderName","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/sendername"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/responses":{"role":"symbol","title":"responses","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ResponseEntity","preciseIdentifier":"s:18headsup_mobile_sdk14ResponseEntityC"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/responses","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/responses"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationEntity":{"role":"symbol","title":"IntegrationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationEntity"}],"abstract":[{"type":"text","text":"Integration Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerEntity":{"role":"symbol","title":"FastingTimerEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerEntity"}],"abstract":[{"type":"text","text":"Fasting Timer Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimerentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/body":{"role":"symbol","title":"body","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/body","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/body"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/messageCount":{"role":"symbol","title":"messageCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/messageCount","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/messagecount"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/isArchived":{"role":"symbol","title":"isArchived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isArchived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/isArchived","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/isarchived"},"doc://com.headsuphealth.headsup-mobile-sdk/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/subject":{"role":"symbol","title":"subject","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/subject","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/subject"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity":{"role":"symbol","title":"SourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceEntity"}],"abstract":[{"type":"text","text":"Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/sourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/tags":{"role":"symbol","title":"tags","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/tags","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/tags"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/attachment":{"role":"symbol","title":"attachment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/attachment","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/attachment"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/likes":{"role":"symbol","title":"likes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"likes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/likes","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/likes"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity":{"role":"symbol","title":"ConversationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntity"}],"abstract":[{"type":"text","text":"Conversation Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceEntity":{"role":"symbol","title":"ManualSourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceEntity"}],"abstract":[{"type":"text","text":"Manual Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/senderUuid":{"role":"symbol","title":"senderUuid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"senderUuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/senderUuid","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/senderuuid"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingEntity":{"role":"symbol","title":"TileSettingEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingEntity"}],"abstract":[{"type":"text","text":"Tile Setting Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/hasAttachment":{"role":"symbol","title":"hasAttachment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAttachment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/hasAttachment","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/hasattachment"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/isRead":{"role":"symbol","title":"isRead","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRead"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/isRead","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/isread"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/recipients":{"role":"symbol","title":"recipients","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipients"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"RecipientEntity","preciseIdentifier":"s:18headsup_mobile_sdk15RecipientEntityC"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/recipients","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/recipients"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/id":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/id","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/id"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/dislikes":{"role":"symbol","title":"dislikes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dislikes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/dislikes","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/dislikes"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/updatedAt":{"role":"symbol","title":"updatedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/updatedAt","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/updatedat"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricEntity":{"role":"symbol","title":"MetricEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricEntity"}],"abstract":[{"type":"text","text":"Metric Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/metricentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientListEntity":{"role":"symbol","title":"ClientListEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientListEntity"}],"abstract":[{"type":"text","text":"Client List Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientListEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/clientlistentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientEntity":{"role":"symbol","title":"ClientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientEntity"}],"abstract":[{"type":"text","text":"Client Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/cliententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity":{"role":"symbol","title":"UserEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"abstract":[{"type":"text","text":"User Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/createdAt":{"role":"symbol","title":"createdAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/createdAt","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/createdat"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationConfigEntity":{"role":"symbol","title":"IntegrationConfigEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationConfigEntity"}],"abstract":[{"type":"text","text":"Integration Config Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationConfigEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationconfigentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity/postedAt":{"role":"symbol","title":"postedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity\/postedAt","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/conversationentity\/postedat"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationRecipientEntity":{"role":"symbol","title":"ConversationRecipientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRecipientEntity"}],"abstract":[{"type":"text","text":"Conversation Recipient Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRecipientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationrecipiententity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/title","value":"MetricEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/fragments","value":[{"kind":"identifier","text":"MetricEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/title","value":"UserEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}