{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can register or log in a user by means of a user id and password, or use Single-Sign-On (SSO) with Apple, Google or Linked In as outlined in the sections below. You can also log them out and check if they are logged in."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserIDPassword"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserSSO"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserIDPassword"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserSSO"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LogoutUser"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoggedInCheck"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/registrationlogin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/registrationlogin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"After installing the Heads Up SDK, the next step in using the SDK’s features is to register and-or log in a user."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Registration, Login and Logout","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegisterUserSSO":{"role":"article","title":"Register a User with Single Sign On (SSO)","abstract":[{"type":"text","text":"This topic shows you how to register a user with Heads Up Cloud Services using Single Sign On"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserSSO","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registerusersso"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LogoutUser":{"role":"article","title":"Log a User Out","abstract":[{"type":"text","text":"Regardless of whether a user has logged in with an id and password or via SSO, you use the same technique to log them out"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LogoutUser","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/logoutuser"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingSDK":{"role":"article","title":"Installing the Heads Up SDK","abstract":[{"type":"text","text":"This topic contains instructions for installing the Heads Up Mobile SDK and integrating it into your mobile project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingsdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSources":{"role":"article","title":"Connecting and Disconnecting Sources","abstract":[{"type":"text","text":"The Heads Up platform integrates with many popular apps and data sources such as Apple Health, Oura, Dexcom and Fitbit. In this article, you’ll learn how to connect and disconnect these various sources."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsources"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ArchitecturalOverview":{"role":"article","title":"Architectural Overview","abstract":[{"type":"text","text":"This article provides an architectural overview of how your app interacts with the Heads Up Mobile SDK to access the functionality of the Heads Up Cloud Platform."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/architecturaloverview"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LoggedInCheck":{"role":"article","title":"Check if a User is Logged In","abstract":[{"type":"text","text":"When your app first starts up, you should normally check if a user is already logged in, and if not, present them with UI to do so."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoggedInCheck","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/loggedincheck"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LoginUserSSO":{"role":"article","title":"Log In with Single Sign On (SSO)","abstract":[{"type":"text","text":"This topic shows you how to log a user into the Heads Up Cloud Services using SSO."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserSSO","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/loginusersso"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithUserData":{"role":"article","title":"Working With User Data","abstract":[{"type":"text","text":"Most of the functionality in the Heads Up Mobile SDK requires access to a user’s data. This topic discusses how to retrieve and update user data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithuserdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RetrievingHealthData":{"role":"collectionGroup","title":"Retrieving Health Data","abstract":[{"type":"text","text":"There us a wealth of data available in the Heads Up platform you can retrieve and manipulate from the Heads Up SDK. This article shows the objects you can use to download this data into your own app."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/LoginUserIDPassword":{"role":"article","title":"Log In with an ID and Password","abstract":[{"type":"text","text":"This topic shows you how to log a user into the Heads Up Cloud Services using an ID and password."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/LoginUserIDPassword","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/loginuseridpassword"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegisterUserIDPassword":{"role":"article","title":"Register a User with User ID and Password","abstract":[{"type":"text","text":"This topic shows you how to register a user with Heads Up cloud services using a User ID and password."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegisterUserIDPassword","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registeruseridpassword"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithAppleHealthKit":{"role":"collectionGroup","title":"Working With Apple HealthKit","abstract":[{"type":"text","text":"Apple’s HealthKit provides a vast array of health information that is accessible through the Heads Up SDK. In this article you’ll learn about the Heads Up SDK objects you can work with to upload and manipulate HealthKit data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}