{"seeAlsoSections":[{"title":"Business Models","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceEntity"}],"title":"SourceEntity","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:18headsup_mobile_sdk12SourceEntityC","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"SourceEntity"}]},"abstract":[{"type":"text","text":"Source Entity"}],"sections":[],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/clazz","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/color","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/displayType","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/existed_tile","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/group","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/icon","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/isSelected","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/name","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/supported_devices","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/url"]}],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/sourceentity"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceEntity"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/init(from:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientEntity":{"role":"symbol","title":"ClientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientEntity"}],"abstract":[{"type":"text","text":"Client Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/cliententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/clazz":{"role":"symbol","title":"clazz","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clazz"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/clazz","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/clazz"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/existed_tile":{"role":"symbol","title":"existed_tile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"existed_tile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/existed_tile","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/existed_tile"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/color":{"role":"symbol","title":"color","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/color","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/color"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/displayType":{"role":"symbol","title":"displayType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayType","preciseIdentifier":"s:18headsup_mobile_sdk11DisplayTypeC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/displayType","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/displaytype"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity":{"role":"symbol","title":"ConversationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntity"}],"abstract":[{"type":"text","text":"Conversation Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/supported_devices":{"role":"symbol","title":"supported_devices","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supported_devices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SelectableItem","preciseIdentifier":"s:18headsup_mobile_sdk14SelectableItemC"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/supported_devices","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/supported_devices"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingEntity":{"role":"symbol","title":"TileSettingEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingEntity"}],"abstract":[{"type":"text","text":"Tile Setting Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/isSelected","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/isselected"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricEntity":{"role":"symbol","title":"MetricEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricEntity"}],"abstract":[{"type":"text","text":"Metric Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/metricentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationConfigEntity":{"role":"symbol","title":"IntegrationConfigEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationConfigEntity"}],"abstract":[{"type":"text","text":"Integration Config Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationConfigEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationconfigentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/group":{"role":"symbol","title":"group","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"group"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/group","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/group"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity":{"role":"symbol","title":"UserEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"abstract":[{"type":"text","text":"User Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/icon":{"role":"symbol","title":"icon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/icon","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/icon"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationRecipientEntity":{"role":"symbol","title":"ConversationRecipientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRecipientEntity"}],"abstract":[{"type":"text","text":"Conversation Recipient Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRecipientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationrecipiententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/name","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/name"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity\/url","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/sourceentity\/url"},"doc://com.headsuphealth.headsup-mobile-sdk/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationEntity":{"role":"symbol","title":"IntegrationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationEntity"}],"abstract":[{"type":"text","text":"Integration Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceEntity":{"role":"symbol","title":"ManualSourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceEntity"}],"abstract":[{"type":"text","text":"Manual Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientListEntity":{"role":"symbol","title":"ClientListEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientListEntity"}],"abstract":[{"type":"text","text":"Client List Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientListEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/clientlistentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity":{"role":"symbol","title":"SourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceEntity"}],"abstract":[{"type":"text","text":"Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/sourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerEntity":{"role":"symbol","title":"FastingTimerEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerEntity"}],"abstract":[{"type":"text","text":"Fasting Timer Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimerentity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/title","value":"MetricEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/fragments","value":[{"kind":"identifier","text":"MetricEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/title","value":"UserEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}