{"seeAlsoSections":[{"title":"Business Models","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"title":"UserEntity","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@headsup_mobile_sdk@objc(cs)UserEntity","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"UserEntity"}]},"abstract":[{"type":"text","text":"User Entity"}],"sections":[],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/activeAccounts","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/avatarFile","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/bloodType","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/displayUpgradeButton","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/dob","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/email","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/entitlements","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/first","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/fullName","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/height","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/humanExternalId","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/id","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/last","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/organizationUuid","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/passwordChangedAt","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/selectedAccount","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/setting","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/sex","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/subscriptionStatus","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/subscriptionType","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/timeZone","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/title","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/trialExpiryDate","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/uuid"]}],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/userentity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/userentity"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/entitlements":{"role":"symbol","title":"entitlements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Entitlements","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)Entitlements"}],"abstract":[{"type":"text","text":"The User’s Entitlements as specified in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/entitlements","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/entitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/sex":{"role":"symbol","title":"sex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sex - Currently only “male” or “female”"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/sex","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/sex"},"doc://com.headsuphealth.headsup-mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationEntity":{"role":"symbol","title":"ConversationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntity"}],"abstract":[{"type":"text","text":"Conversation Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements":{"role":"symbol","title":"Entitlements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Entitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Entitlements"}],"url":"\/documentation\/headsup_mobile_sdk\/entitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingEntity":{"role":"symbol","title":"TileSettingEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingEntity"}],"abstract":[{"type":"text","text":"Tile Setting Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/dob":{"role":"symbol","title":"dob","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dob"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Date of birth yyyy-mm-dd"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/dob","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/dob"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/email":{"role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Email"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/email","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/email"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/height":{"role":"symbol","title":"height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Height in cm"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/height","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/height"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity":{"role":"symbol","title":"UserEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"abstract":[{"type":"text","text":"User Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userentity"},"doc://com.headsuphealth.headsup-mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/bloodType":{"role":"symbol","title":"bloodType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bloodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StringLiteralType","preciseIdentifier":"s:s17StringLiteralTypea"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Blood type"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/bloodType","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/bloodtype"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricEntity":{"role":"symbol","title":"MetricEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricEntity"}],"abstract":[{"type":"text","text":"Metric Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/metricentity"},"doc://com.headsuphealth.headsup-mobile-sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP"},"doc://com.headsuphealth.headsup-mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationEntity":{"role":"symbol","title":"IntegrationEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationEntity"}],"abstract":[{"type":"text","text":"Integration Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationConfigEntity":{"role":"symbol","title":"IntegrationConfigEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationConfigEntity"}],"abstract":[{"type":"text","text":"Integration Config Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationConfigEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationconfigentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/organizationUuid":{"role":"symbol","title":"organizationUuid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"organizationUuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Organization uuid if a user belongs to an organization, othewise empty"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/organizationUuid","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/organizationuuid"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/uuid":{"role":"symbol","title":"uuid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"New unique user id"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/uuid","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/uuid"},"doc://com.headsuphealth.headsup-mobile-sdk/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceEntity":{"role":"symbol","title":"ManualSourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceEntity"}],"abstract":[{"type":"text","text":"Manual Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/activeAccounts":{"role":"symbol","title":"activeAccounts","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAccounts"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]]?"}],"abstract":[{"type":"text","text":"An array of the user’s active accounts"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/activeAccounts","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/activeaccounts"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Title"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/title","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/title"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/timeZone":{"role":"symbol","title":"timeZone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Time zone in Ruby on Rails"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/timeZone","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/timezone"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/last":{"role":"symbol","title":"last","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"last"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Last name"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/last","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/last"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserSetting":{"role":"symbol","title":"UserSetting","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserSetting"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserSetting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserSetting"}],"url":"\/documentation\/headsup_mobile_sdk\/usersetting"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationRecipientEntity":{"role":"symbol","title":"ConversationRecipientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRecipientEntity"}],"abstract":[{"type":"text","text":"Conversation Recipient Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRecipientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationrecipiententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/first":{"role":"symbol","title":"first","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"first"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"First name"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/first","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/first"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/setting":{"role":"symbol","title":"setting","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserSetting","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)UserSetting"}],"abstract":[{"type":"text","text":"The User’s Unit-of-Measure Settings as specified in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserSetting"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/setting","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/setting"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/id":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Unique user id"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/id","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/id"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/displayUpgradeButton":{"role":"symbol","title":"displayUpgradeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayUpgradeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"True if an upgrade button should be displayed in the user’s profile"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/displayUpgradeButton","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/displayupgradebutton"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/passwordChangedAt":{"role":"symbol","title":"passwordChangedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"passwordChangedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Date\/Time stamp of last time the user’s password was changed"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/passwordChangedAt","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/passwordchangedat"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceEntity":{"role":"symbol","title":"SourceEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceEntity"}],"abstract":[{"type":"text","text":"Source Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/sourceentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/fullName":{"role":"symbol","title":"fullName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The User’s full name"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/fullName","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/fullname"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/avatarFile":{"role":"symbol","title":"avatarFile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatarFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Url of user’s avatar file"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/avatarFile","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/avatarfile"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientEntity":{"role":"symbol","title":"ClientEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientEntity"}],"abstract":[{"type":"text","text":"Client Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/cliententity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/selectedAccount":{"role":"symbol","title":"selectedAccount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The currently selected user account"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/selectedAccount","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/selectedaccount"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerEntity":{"role":"symbol","title":"FastingTimerEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerEntity"}],"abstract":[{"type":"text","text":"Fasting Timer Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimerentity"},"doc://com.headsuphealth.headsup-mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/trialExpiryDate":{"role":"symbol","title":"trialExpiryDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trialExpiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Trial expiration date"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/trialExpiryDate","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/trialexpirydate"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientListEntity":{"role":"symbol","title":"ClientListEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientListEntity"}],"abstract":[{"type":"text","text":"Client List Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientListEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientListEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/clientlistentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/init(from:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/subscriptionType":{"role":"symbol","title":"subscriptionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriptionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Subscription type"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/subscriptionType","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/subscriptiontype"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/humanExternalId":{"role":"symbol","title":"humanExternalId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"humanExternalId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Human API external id"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/humanExternalId","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/humanexternalid"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity/subscriptionStatus":{"role":"symbol","title":"subscriptionStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriptionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Subscription status"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity\/subscriptionStatus","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/userentity\/subscriptionstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"UserEntity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UserEntity"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Business Models","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/title","value":"Entitlements"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/fragments","value":[{"kind":"identifier","text":"Entitlements"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/title","value":"UserEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/title","value":"MetricEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/fragments","value":[{"kind":"identifier","text":"MetricEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserSetting\/title","value":"UserSetting"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserSetting\/fragments","value":[{"kind":"identifier","text":"UserSetting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}