{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The primary classes you’ll use when working with user data are the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"},{"type":"text","text":" classes."}]},{"anchor":"Retrieving-a-Users-Data","level":3,"type":"heading","text":"Retrieving a User’s Data"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController"},{"type":"text","text":" class is a Singleton that’s accessed via its "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property. You use its "},{"type":"strong","inlineContent":[{"type":"text","text":"getUserInfo()"}]},{"type":"text","text":" method to retrieve a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity"},{"type":"text","text":" that contains everything you need to know about a user."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/getUserInfo(completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.getUserInfo { entity, errorMessage in","    \/\/ Do something with the returned **UserEntity** object.","}"]},{"anchor":"Updating-a-Users-Data","level":3,"type":"heading","text":"Updating a User’s Data"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use the "},{"type":"strong","inlineContent":[{"type":"text","text":"UserController.updateUserInfo()"}]},{"type":"text","text":" method to update a user’s data, passing in a UserEntity object that contains the updated data."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserInfo(userInfo:completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.updateUserInfo(userInfo: UserController.userEntity!) { ","    success, responseJSON in","","}"]},{"anchor":"Updating-a-Users-Email","level":3,"type":"heading","text":"Updating a User’s Email"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use the "},{"type":"strong","inlineContent":[{"type":"text","text":"UserController.updateUserEmail()"}]},{"type":"text","text":" method to update a user’s email."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserEmail(email:completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.updateUserEmail(email: email) { ","    responseJSON, errorMessage in","","}"]},{"anchor":"Updating-a-Users-Password","level":3,"type":"heading","text":"Updating a User’s Password"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use the "},{"type":"strong","inlineContent":[{"type":"text","text":"UserController.updateUserPassword()"}]},{"type":"text","text":" method to update a user’s password."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserPassword(newPassword:currentPassword:completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.updateUserPassword(newPassword: self.txtNewPassword.text!, ","    currentPassword: password) { ","    responseJSON, errorMessage in","","}"]},{"anchor":"Updating-a-Users-Units","level":3,"type":"heading","text":"Updating a User’s Units"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use the "},{"type":"strong","inlineContent":[{"type":"text","text":"UserController.updateUserUnits()"}]},{"type":"text","text":" method to update a user’s units, passing in a UserEntity object that contains the updated units."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserUnits(userInfo:completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.updateUserUnits(userInfo: UserController.userEntity!) { ","    success, responeJSON in","","}"]},{"anchor":"Retrieving-a-Users-Avatar-Image","level":3,"type":"heading","text":"Retrieving a User’s Avatar Image"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use the "},{"type":"strong","inlineContent":[{"type":"text","text":"UserController.downloadUserAvatarImage()"}]},{"type":"text","text":" method to retrieve a user’s avatar image’."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/downloadUserAvatarImage(urlString:completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.downloadUserAvatarImage(urlString: avatarFile) { ","    image, error in","    ","}"]},{"anchor":"Uploading-a-Users-Avatar-Image","level":3,"type":"heading","text":"Uploading a User’s Avatar Image"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use the "},{"type":"strong","inlineContent":[{"type":"text","text":"UserController.uploadUserAvatarImage()"}]},{"type":"text","text":" method to upload a user’s avatar image’."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/uploadUserAvatarImage(image:completion:)"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.uploadUserAvatarImage(image: image) { ","    success, responseJSON in","    "," }"]},{"anchor":"Deleting-a-Users-Account","level":3,"type":"heading","text":"Deleting a User’s Account"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To delete the currently logged in user’s account, you use the "},{"type":"strong","inlineContent":[{"type":"text","text":"UserController.deleteUserAccount()"}]},{"type":"text","text":" method."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example"}]}]},{"type":"codeListing","syntax":"swift","code":["UserController.shared.deleteUserAccount { success, errorMessage in","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/workingwithuserdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/workingwithuserdata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Most of the functionality in the Heads Up Mobile SDK requires access to a user’s data. This topic discusses how to retrieve and update user data."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Working With User Data","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController/updateUserUnits(userInfo:completion:)":{"role":"symbol","title":"updateUserUnits(userInfo:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserUnits"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserEntity","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)UserEntity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"responseJSON"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates the user’s units based on the values in the specified "},{"type":"codeVoice","code":"ÙserEntity"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserUnits(userInfo:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/usercontroller\/updateuserunits(userinfo:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RetrievingHealthData":{"role":"collectionGroup","title":"Retrieving Health Data","abstract":[{"type":"text","text":"There us a wealth of data available in the Heads Up platform you can retrieve and manipulate from the Heads Up SDK. This article shows the objects you can use to download this data into your own app."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithAppleHealthKit":{"role":"collectionGroup","title":"Working With Apple HealthKit","abstract":[{"type":"text","text":"Apple’s HealthKit provides a vast array of health information that is accessible through the Heads Up SDK. In this article you’ll learn about the Heads Up SDK objects you can work with to upload and manipulate HealthKit data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController/uploadUserAvatarImage(image:completion:)":{"role":"symbol","title":"uploadUserAvatarImage(image:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadUserAvatarImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"responeJSON"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Uploads the specified avatar image for the current user"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/uploadUserAvatarImage(image:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/usercontroller\/uploaduseravatarimage(image:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegistrationLogin":{"role":"article","title":"Registration, Login and Logout","abstract":[{"type":"text","text":"After installing the Heads Up SDK, the next step in using the SDK’s features is to register and-or log in a user."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registrationlogin"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSources":{"role":"article","title":"Connecting and Disconnecting Sources","abstract":[{"type":"text","text":"The Heads Up platform integrates with many popular apps and data sources such as Apple Health, Oura, Dexcom and Fitbit. In this article, you’ll learn how to connect and disconnect these various sources."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsources"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController":{"role":"symbol","title":"UserController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserController"}],"abstract":[{"type":"text","text":"User Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserController"}],"url":"\/documentation\/headsup_mobile_sdk\/usercontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController/updateUserEmail(email:completion:)":{"role":"symbol","title":"updateUserEmail(email:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserEmail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"responeJSON"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update the user’s email address"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserEmail(email:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/usercontroller\/updateuseremail(email:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController/downloadUserAvatarImage(urlString:completion:)":{"role":"symbol","title":"downloadUserAvatarImage(urlString:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadUserAvatarImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"urlString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Download the user’s avatar image from the specified url string"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/downloadUserAvatarImage(urlString:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/usercontroller\/downloaduseravatarimage(urlstring:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ArchitecturalOverview":{"role":"article","title":"Architectural Overview","abstract":[{"type":"text","text":"This article provides an architectural overview of how your app interacts with the Heads Up Mobile SDK to access the functionality of the Heads Up Cloud Platform."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/architecturaloverview"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController/updateUserInfo(userInfo:completion:)":{"role":"symbol","title":"updateUserInfo(userInfo:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserEntity","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)UserEntity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"responseJSON"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates the user’s information from the values in the specified "},{"type":"codeVoice","code":"ÙserEntity"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserInfo(userInfo:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/usercontroller\/updateuserinfo(userinfo:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController/getUserInfo(completion:)":{"role":"symbol","title":"getUserInfo(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:18headsup_mobile_sdk14UserControllerC1Txmfp"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets the current user’s "},{"type":"codeVoice","code":"ÙserEntity"},{"type":"text","text":" information"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/getUserInfo(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/usercontroller\/getuserinfo(completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController/updateUserPassword(newPassword:currentPassword:completion:)":{"role":"symbol","title":"updateUserPassword(newPassword:currentPassword:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserPassword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"newPassword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentPassword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"responeJSON"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates the current user’s password"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController\/updateUserPassword(newPassword:currentPassword:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/usercontroller\/updateuserpassword(newpassword:currentpassword:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserEntity":{"role":"symbol","title":"UserEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserEntity"}],"abstract":[{"type":"text","text":"User Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/userentity"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingSDK":{"role":"article","title":"Installing the Heads Up SDK","abstract":[{"type":"text","text":"This topic contains instructions for installing the Heads Up Mobile SDK and integrating it into your mobile project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/title","value":"UserEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1UserEntity\/fragments","value":[{"kind":"identifier","text":"UserEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}