{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)Entitlements","text":"Entitlements"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/defaultentitlements\/entitlements"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements\/entitlements","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Entitlements","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)Entitlements"}],"title":"entitlements","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:18headsup_mobile_sdk19DefaultEntitlementsC12entitlementsAA0E0Cvp","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements"]]},"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DefaultEntitlements/entitlements":{"role":"symbol","title":"entitlements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Entitlements","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)Entitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements\/entitlements","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/defaultentitlements\/entitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements":{"role":"symbol","title":"Entitlements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Entitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Entitlements"}],"url":"\/documentation\/headsup_mobile_sdk\/entitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DefaultEntitlements":{"role":"symbol","title":"DefaultEntitlements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultEntitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultEntitlements"}],"url":"\/documentation\/headsup_mobile_sdk\/defaultentitlements"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/title","value":"Entitlements"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/fragments","value":[{"kind":"identifier","text":"Entitlements"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1DefaultEntitlements\/title","value":"DefaultEntitlements"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1DefaultEntitlements\/fragments","value":[{"kind":"identifier","text":"DefaultEntitlements"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}