{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The diagram below provides a high-level overview of the Heads Up SDK and cloud architecture, that demonstrates the universe of possible ways your app to interact with the Heads Up platform."},{"type":"text","text":" "},{"type":"image","identifier":"HeadsUpPlatformArchitecture.png"}]},{"anchor":"Third-Party-Client-Mobile-App","level":3,"type":"heading","text":"Third Party Client Mobile App"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The large green rectangle on the left side of the diagram represents your mobile app."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"Client App UI"}]},{"type":"text","text":" represents your app’s’ user interface, which you create for your user’s to interact with your mobile app."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"Client App Logic"}]},{"type":"text","text":" represents the core logic of your application where you write code that accesses the "},{"type":"strong","inlineContent":[{"type":"text","text":"Heads Up SDK"}]},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"Heads Up SDK"}]},{"type":"text","text":" is our Swift Framework, containing all of the high level objects you need to perform important tasks such as registering and authenticating users, connecting and disconnecting apps and devices, as well as interacting with the HealthKit SDK. The Heads Up SDK interacts with the Heads Up cloud services providing a higher level API for your mobile app."}]}]}]},{"anchor":"Heads-Up-Backend","level":3,"type":"heading","text":"Heads Up Backend"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The blue rectangle in the bottom right corner represents the Heads Up Backend, or Cloud Services. It contains components that provide the core functionality of the Heads Up Cloud Services that are typically called directly from the Heads Up Mobile SDK that are used to upload, retrieve and update user’s data. It also contains "},{"type":"strong","inlineContent":[{"type":"text","text":"Authentication"}]},{"type":"text","text":" logic that is used to authenticate users via id\/password or SSO."}]},{"anchor":"Optional-SSO-Auth-Service","level":3,"type":"heading","text":"Optional SSO Auth Service"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The yellow rectangle represents Heads Up optional SSO Auth Service that is used to authorize users. The currently supported SSO options are Google, Apple, and LinkedIn."}]},{"anchor":"Client-Backend","level":3,"type":"heading","text":"Client Backend"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The green rectangle in the upper right corner of the diagram represents your optional back end server. Although you can rely completely on the Heads Up Backend cloud services, your mobile app may also connect to your own backend server’s API’s and authentication services. Note that your back end server can optionally call Heads Up Cloud Services directly."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/architecturaloverview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/architecturaloverview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article provides an architectural overview of how your app interacts with the Heads Up Mobile SDK to access the functionality of the Heads Up Cloud Platform."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Architectural Overview","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithUserData":{"role":"article","title":"Working With User Data","abstract":[{"type":"text","text":"Most of the functionality in the Heads Up Mobile SDK requires access to a user’s data. This topic discusses how to retrieve and update user data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithuserdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RetrievingHealthData":{"role":"collectionGroup","title":"Retrieving Health Data","abstract":[{"type":"text","text":"There us a wealth of data available in the Heads Up platform you can retrieve and manipulate from the Heads Up SDK. This article shows the objects you can use to download this data into your own app."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"},"HeadsUpPlatformArchitecture.png":{"alt":"HeadsUp Logo","type":"image","identifier":"HeadsUpPlatformArchitecture.png","variants":[{"url":"\/images\/HeadsUpPlatformArchitecture.png","traits":["1x","light"]}]},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithAppleHealthKit":{"role":"collectionGroup","title":"Working With Apple HealthKit","abstract":[{"type":"text","text":"Apple’s HealthKit provides a vast array of health information that is accessible through the Heads Up SDK. In this article you’ll learn about the Heads Up SDK objects you can work with to upload and manipulate HealthKit data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegistrationLogin":{"role":"article","title":"Registration, Login and Logout","abstract":[{"type":"text","text":"After installing the Heads Up SDK, the next step in using the SDK’s features is to register and-or log in a user."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registrationlogin"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingSDK":{"role":"article","title":"Installing the Heads Up SDK","abstract":[{"type":"text","text":"This topic contains instructions for installing the Heads Up Mobile SDK and integrating it into your mobile project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingsdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSources":{"role":"article","title":"Connecting and Disconnecting Sources","abstract":[{"type":"text","text":"The Heads Up platform integrates with many popular apps and data sources such as Apple Health, Oura, Dexcom and Fitbit. In this article, you’ll learn how to connect and disconnect these various sources."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsources"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}