{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultEntitlements"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/defaultentitlements"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/defaultentitlements"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements\/entitlements"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultEntitlements"}],"title":"DefaultEntitlements","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@headsup_mobile_sdk@objc(cs)DefaultEntitlements","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultEntitlements"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"references":{"doc://com.headsuphealth.headsup-mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DefaultEntitlements/entitlements":{"role":"symbol","title":"entitlements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Entitlements","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)Entitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements\/entitlements","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/defaultentitlements\/entitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"},"doc://com.headsuphealth.headsup-mobile-sdk/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DefaultEntitlements":{"role":"symbol","title":"DefaultEntitlements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultEntitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultEntitlements"}],"url":"\/documentation\/headsup_mobile_sdk\/defaultentitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ"},"doc://com.headsuphealth.headsup-mobile-sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP"},"doc://com.headsuphealth.headsup-mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/DefaultEntitlements/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/DefaultEntitlements\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/defaultentitlements\/init(from:)"},"doc://com.headsuphealth.headsup-mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DefaultEntitlements"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DefaultEntitlements"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DefaultEntitlements"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultEntitlements"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1DefaultEntitlements\/title","value":"DefaultEntitlements"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1DefaultEntitlements\/fragments","value":[{"kind":"identifier","text":"DefaultEntitlements"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}