{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Entitlements"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/entitlements"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/entitlements"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/cancel_user_account_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/client_food_journal_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/client_notes_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/custom_dark_logo","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/custom_light_logo","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/dashboard_locked","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/data_connections_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/devices_allowed","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/messaging_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_about_page_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_help_center_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_integrations_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_lab_results_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_learn_page_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_messaging_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_privacy_link","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_records_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_reports_enabled","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_terms_link","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/sso_identity_providers","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/user_org_name","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/user_org_role"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Entitlements"}],"title":"Entitlements","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@headsup_mobile_sdk@objc(cs)Entitlements","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"Entitlements"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/dashboard_locked":{"role":"symbol","title":"dashboard_locked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dashboard_locked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/dashboard_locked","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/dashboard_locked"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/devices_allowed":{"role":"symbol","title":"devices_allowed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"devices_allowed"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/devices_allowed","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/devices_allowed"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_integrations_enabled":{"role":"symbol","title":"mobile_integrations_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_integrations_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_integrations_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_integrations_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/custom_dark_logo":{"role":"symbol","title":"custom_dark_logo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom_dark_logo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/custom_dark_logo","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/custom_dark_logo"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_messaging_enabled":{"role":"symbol","title":"mobile_messaging_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_messaging_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_messaging_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_messaging_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/custom_light_logo":{"role":"symbol","title":"custom_light_logo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom_light_logo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/custom_light_logo","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/custom_light_logo"},"doc://com.headsuphealth.headsup-mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ"},"doc://com.headsuphealth.headsup-mobile-sdk/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/Se"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_help_center_enabled":{"role":"symbol","title":"mobile_help_center_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_help_center_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_help_center_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_help_center_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/user_org_name":{"role":"symbol","title":"user_org_name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"user_org_name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/user_org_name","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/user_org_name"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/messaging_enabled":{"role":"symbol","title":"messaging_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/messaging_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/messaging_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_records_enabled":{"role":"symbol","title":"mobile_records_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_records_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_records_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_records_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/client_food_journal_enabled":{"role":"symbol","title":"client_food_journal_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"client_food_journal_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/client_food_journal_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/client_food_journal_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_privacy_link":{"role":"symbol","title":"mobile_privacy_link","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_privacy_link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_privacy_link","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_privacy_link"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/user_org_role":{"role":"symbol","title":"user_org_role","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"user_org_role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/user_org_role","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/user_org_role"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_terms_link":{"role":"symbol","title":"mobile_terms_link","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_terms_link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_terms_link","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_terms_link"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_reports_enabled":{"role":"symbol","title":"mobile_reports_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_reports_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_reports_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_reports_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/data_connections_enabled":{"role":"symbol","title":"data_connections_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data_connections_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/data_connections_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/data_connections_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/client_notes_enabled":{"role":"symbol","title":"client_notes_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"client_notes_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/client_notes_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/client_notes_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_about_page_enabled":{"role":"symbol","title":"mobile_about_page_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_about_page_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_about_page_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_about_page_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_learn_page_enabled":{"role":"symbol","title":"mobile_learn_page_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_learn_page_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_learn_page_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_learn_page_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/mobile_lab_results_enabled":{"role":"symbol","title":"mobile_lab_results_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobile_lab_results_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/mobile_lab_results_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/mobile_lab_results_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements":{"role":"symbol","title":"Entitlements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Entitlements"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Entitlements"}],"url":"\/documentation\/headsup_mobile_sdk\/entitlements"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/init(from:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/headsup_mobile_sdk\/entitlements\/init"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/sso_identity_providers":{"role":"symbol","title":"sso_identity_providers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sso_identity_providers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/sso_identity_providers","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/sso_identity_providers"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Entitlements/cancel_user_account_enabled":{"role":"symbol","title":"cancel_user_account_enabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel_user_account_enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/cancel_user_account_enabled","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/entitlements\/cancel_user_account_enabled"},"doc://com.headsuphealth.headsup-mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.headsuphealth.headsup-mobile-sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Entitlements"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Entitlements"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Entitlements"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Entitlements\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Entitlements"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/title","value":"Entitlements"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1Entitlements\/fragments","value":[{"kind":"identifier","text":"Entitlements"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}