{"seeAlsoSections":[{"title":"Business Controllers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Graph","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MessagingConversationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PhotoJournalConversationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"}],"title":"HealthKit","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@headsup_mobile_sdk@objc(cs)HealthKit","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"HealthKit"}]},"abstract":[{"type":"text","text":"The primary HealthKit class"}],"sections":[],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/clearAnchors(forUser:metricKey:callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/initHealthKit(input:callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isAvailable(callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isHealthKitConnectedOnServer(callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/uploadHealthKitData(input:callback:)"]}],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/healthkit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/healthkit"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerController":{"role":"symbol","title":"FastingTimerController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerController"}],"abstract":[{"type":"text","text":"Fasting Timer Business Controller - Singleton accessed via "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerController"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimercontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s7CVarArgP"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController":{"role":"symbol","title":"IntegrationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationController"}],"abstract":[{"type":"text","text":"\/\/\/ Integration Business Controller - API for Heads Up integration sources such as  Oura, Dexcom, Fitbit, etc."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingController":{"role":"symbol","title":"TileSettingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingController"}],"abstract":[{"type":"text","text":"Tile Setting Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingController"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientController":{"role":"symbol","title":"ClientController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientController"}],"abstract":[{"type":"text","text":"Client Business Controller - Single accessed via the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientController"}],"url":"\/documentation\/headsup_mobile_sdk\/clientcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Graph":{"role":"symbol","title":"Graph","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Graph"}],"abstract":[{"type":"text","text":"Graph Business Controller"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Graph","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Graph"}],"url":"\/documentation\/headsup_mobile_sdk\/graph"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController":{"role":"symbol","title":"UserController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserController"}],"abstract":[{"type":"text","text":"User Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserController"}],"url":"\/documentation\/headsup_mobile_sdk\/usercontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit":{"role":"symbol","title":"HealthKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"}],"abstract":[{"type":"text","text":"The primary HealthKit class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HealthKit"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit/uploadHealthKitData(input:callback:)":{"role":"symbol","title":"uploadHealthKitData(input:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadHealthKitData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"input"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/uploadHealthKitData(input:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uploadHealthKitDataWithInput:callback:"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit\/uploadhealthkitdata(input:callback:)"},"doc://com.headsuphealth.headsup-mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController":{"role":"symbol","title":"MetricController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricController"}],"abstract":[{"type":"text","text":"Metric Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricController"}],"url":"\/documentation\/headsup_mobile_sdk\/metriccontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MessagingConversationController":{"role":"symbol","title":"MessagingConversationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingConversationController"}],"abstract":[{"type":"text","text":"Photo Journal Conversation Business Controller - Singleton accessed via the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MessagingConversationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingConversationController"}],"url":"\/documentation\/headsup_mobile_sdk\/messagingconversationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit/isHealthKitConnectedOnServer(callback:)":{"role":"symbol","title":"isHealthKitConnectedOnServer(callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHealthKitConnectedOnServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isHealthKitConnectedOnServer(callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isHealthKitConnectedOnServerWithCallback:"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit\/ishealthkitconnectedonserver(callback:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit/initHealthKit(input:callback:)":{"role":"symbol","title":"initHealthKit(input:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initHealthKit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"input"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/initHealthKit(input:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initHealthKitWithInput:callback:"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit\/inithealthkit(input:callback:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceController":{"role":"symbol","title":"SourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceController"}],"abstract":[{"type":"text","text":"Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/sourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationConfigController":{"role":"symbol","title":"IntegrationConfigController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationConfigController"}],"abstract":[{"type":"text","text":"Integration Config Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationConfigController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationconfigcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit/isAvailable(callback:)":{"role":"symbol","title":"isAvailable(callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isAvailable(callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAvailableWithCallback:"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit\/isavailable(callback:)"},"doc://com.headsuphealth.headsup-mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/PhotoJournalConversationController":{"role":"symbol","title":"PhotoJournalConversationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoJournalConversationController"}],"abstract":[{"type":"text","text":"Photo Journal Conversation Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PhotoJournalConversationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhotoJournalConversationController"}],"url":"\/documentation\/headsup_mobile_sdk\/photojournalconversationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit/clearAnchors(forUser:metricKey:callback:)":{"role":"symbol","title":"clearAnchors(forUser:metricKey:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearAnchors"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metricKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/clearAnchors(forUser:metricKey:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearAnchorsForUser:metricKey:callback:"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit\/clearanchors(foruser:metrickey:callback:)"},"doc://com.headsuphealth.headsup-mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SH"},"doc://com.headsuphealth.headsup-mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/SQ"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceController":{"role":"symbol","title":"ManualSourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceController"}],"abstract":[{"type":"text","text":"Manual Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(pl)NSObject"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationRecipientController":{"role":"symbol","title":"ConversationRecipientController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRecipientController"}],"abstract":[{"type":"text","text":"Conversation Recipient Business Controller - Singleton accessed via "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRecipientController"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationrecipientcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HealthKit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HealthKit"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HealthKit"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/clearAnchors(forUser:metricKey:callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/initHealthKit(input:callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isAvailable(callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isHealthKitConnectedOnServer(callback:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/uploadHealthKitData(input:callback:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/title","value":"HealthKit"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/fragments","value":[{"kind":"identifier","text":"HealthKit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1uploadHealthKitData(input:callback:)\/title","value":"uploadHealthKitDataWithInput:callback:"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1uploadHealthKitData(input:callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"uploadHealthKitDataWithInput:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1isHealthKitConnectedOnServer(callback:)\/title","value":"isHealthKitConnectedOnServerWithCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1isHealthKitConnectedOnServer(callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isHealthKitConnectedOnServerWithCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1initHealthKit(input:callback:)\/title","value":"initHealthKitWithInput:callback:"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1initHealthKit(input:callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initHealthKitWithInput:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1isAvailable(callback:)\/title","value":"isAvailableWithCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1isAvailable(callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isAvailableWithCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1clearAnchors(forUser:metricKey:callback:)\/title","value":"clearAnchorsForUser:metricKey:callback:"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1clearAnchors(forUser:metricKey:callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearAnchorsForUser:metricKey:callback:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}