{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Heads Up Mobile SDK is a Swift framework you can access from a variety of mobile app projects such as Swift, Objective-C, Flutter and React Native."}]},{"anchor":"Integrating-the-Heads-Up-Mobile-SDK","level":3,"type":"heading","text":"Integrating the Heads Up Mobile SDK"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingFlutter"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/installingsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/installingsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingSDK","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This topic contains instructions for installing the Heads Up Mobile SDK and integrating it into your mobile project."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Installing the Heads Up SDK","role":"article","modules":[{"name":"headsup_mobile_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/InstallingFlutter":{"role":"article","title":"Integrating the Heads Up SDK in a Flutter Project","abstract":[{"type":"text","text":"This topic contains instructions on integrating the Heads Up Mobile SDK in a Flutter project."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/InstallingFlutter","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/installingflutter"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ArchitecturalOverview":{"role":"article","title":"Architectural Overview","abstract":[{"type":"text","text":"This article provides an architectural overview of how your app interacts with the Heads Up Mobile SDK to access the functionality of the Heads Up Cloud Platform."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/architecturaloverview"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RegistrationLogin":{"role":"article","title":"Registration, Login and Logout","abstract":[{"type":"text","text":"After installing the Heads Up SDK, the next step in using the SDK’s features is to register and-or log in a user."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/registrationlogin"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithUserData":{"role":"article","title":"Working With User Data","abstract":[{"type":"text","text":"Most of the functionality in the Heads Up Mobile SDK requires access to a user’s data. This topic discusses how to retrieve and update user data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithuserdata"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConnectingSources":{"role":"article","title":"Connecting and Disconnecting Sources","abstract":[{"type":"text","text":"The Heads Up platform integrates with many popular apps and data sources such as Apple Health, Oura, Dexcom and Fitbit. In this article, you’ll learn how to connect and disconnect these various sources."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/connectingsources"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/WorkingWithAppleHealthKit":{"role":"collectionGroup","title":"Working With Apple HealthKit","abstract":[{"type":"text","text":"Apple’s HealthKit provides a vast array of health information that is accessible through the Heads Up SDK. In this article you’ll learn about the Heads Up SDK objects you can work with to upload and manipulate HealthKit data."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/workingwithapplehealthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/RetrievingHealthData":{"role":"collectionGroup","title":"Retrieving Health Data","abstract":[{"type":"text","text":"There us a wealth of data available in the Heads Up platform you can retrieve and manipulate from the Heads Up SDK. This article shows the objects you can use to download this data into your own app."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData","kind":"article","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/retrievinghealthdata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ArchitecturalOverview","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RegistrationLogin","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithUserData","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConnectingSources","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/WorkingWithAppleHealthKit","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/RetrievingHealthData"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}