{"seeAlsoSections":[{"title":"Business Controllers","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Graph","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MessagingConversationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PhotoJournalConversationController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricController"}],"title":"MetricController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:18headsup_mobile_sdk16MetricControllerC","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"MetricController"}]},"abstract":[{"type":"text","text":"Metric Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"sections":[],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BusinessController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/createMetric(url:metricDictionary:completion:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/deleteMetric(url:id:completion:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getMetricByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getMetricDictionaryByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getUserUnit(unitOfMeasure:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getValueMinMaxTotalCountForMetrics(metricList:url:displayPrecision:dailyAggregation:)","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/updateMetric(url:id:metricDictionary:completion:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/shared"]}],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/metriccontroller"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricController"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)MetricEntity","text":"MetricEntity"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController":{"role":"symbol","title":"MetricController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricController"}],"abstract":[{"type":"text","text":"Metric Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricController"}],"url":"\/documentation\/headsup_mobile_sdk\/metriccontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationController":{"role":"symbol","title":"IntegrationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationController"}],"abstract":[{"type":"text","text":"\/\/\/ Integration Business Controller - API for Heads Up integration sources such as  Oura, Dexcom, Fitbit, etc."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MessagingConversationController":{"role":"symbol","title":"MessagingConversationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingConversationController"}],"abstract":[{"type":"text","text":"Photo Journal Conversation Business Controller - Singleton accessed via the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MessagingConversationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingConversationController"}],"url":"\/documentation\/headsup_mobile_sdk\/messagingconversationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceStringValueOptions":{"role":"symbol","title":"ManualSourceStringValueOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceStringValueOptions"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceStringValueOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceStringValueOptions"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourcestringvalueoptions"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/createMetric(url:metricDictionary:completion:)":{"role":"symbol","title":"createMetric(url:metricDictionary:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMetric"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metricDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:18headsup_mobile_sdk16MetricControllerC1Txmfp"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new metric of the specified type"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/createMetric(url:metricDictionary:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/createmetric(url:metricdictionary:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit":{"role":"symbol","title":"HealthKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"}],"abstract":[{"type":"text","text":"The primary HealthKit class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HealthKit"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/getValueMinMaxTotalCountForMetrics(metricList:url:displayPrecision:dailyAggregation:)":{"role":"symbol","title":"getValueMinMaxTotalCountForMetrics(metricList:url:displayPrecision:dailyAggregation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getValueMinMaxTotalCountForMetrics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"metricList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MetricEntity","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)MetricEntity"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayPrecision"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dailyAggregation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> (value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?, secondaryValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?, min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?, max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?, total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?, count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Gets the min\/max total count for metrics in the specified list"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getValueMinMaxTotalCountForMetrics(metricList:url:displayPrecision:dailyAggregation:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/getvalueminmaxtotalcountformetrics(metriclist:url:displayprecision:dailyaggregation:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/UserController":{"role":"symbol","title":"UserController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserController"}],"abstract":[{"type":"text","text":"User Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/UserController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserController"}],"url":"\/documentation\/headsup_mobile_sdk\/usercontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/BusinessController":{"role":"symbol","title":"BusinessController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessController"}],"abstract":[{"type":"text","text":"Base Class of all Business Controllers"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/BusinessController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusinessController"}],"url":"\/documentation\/headsup_mobile_sdk\/businesscontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/IntegrationConfigController":{"role":"symbol","title":"IntegrationConfigController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntegrationConfigController"}],"abstract":[{"type":"text","text":"Integration Config Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/IntegrationConfigController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntegrationConfigController"}],"url":"\/documentation\/headsup_mobile_sdk\/integrationconfigcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/SourceController":{"role":"symbol","title":"SourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceController"}],"abstract":[{"type":"text","text":"Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/SourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/sourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MetricController","preciseIdentifier":"s:18headsup_mobile_sdk16MetricControllerC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MetricEntity","preciseIdentifier":"c:@M@headsup_mobile_sdk@objc(cs)MetricEntity"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Singleton access property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/shared","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/shared"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ClientController":{"role":"symbol","title":"ClientController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientController"}],"abstract":[{"type":"text","text":"Client Business Controller - Single accessed via the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ClientController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientController"}],"url":"\/documentation\/headsup_mobile_sdk\/clientcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/Graph":{"role":"symbol","title":"Graph","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Graph"}],"abstract":[{"type":"text","text":"Graph Business Controller"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/Graph","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Graph"}],"url":"\/documentation\/headsup_mobile_sdk\/graph"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/FastingTimerController":{"role":"symbol","title":"FastingTimerController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FastingTimerController"}],"abstract":[{"type":"text","text":"Fasting Timer Business Controller - Singleton accessed via "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/FastingTimerController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FastingTimerController"}],"url":"\/documentation\/headsup_mobile_sdk\/fastingtimercontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/PhotoJournalConversationController":{"role":"symbol","title":"PhotoJournalConversationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoJournalConversationController"}],"abstract":[{"type":"text","text":"Photo Journal Conversation Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/PhotoJournalConversationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhotoJournalConversationController"}],"url":"\/documentation\/headsup_mobile_sdk\/photojournalconversationcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ManualSourceController":{"role":"symbol","title":"ManualSourceController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManualSourceController"}],"abstract":[{"type":"text","text":"Manual Source Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManualSourceController"}],"url":"\/documentation\/headsup_mobile_sdk\/manualsourcecontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/deleteMetric(url:id:completion:)":{"role":"symbol","title":"deleteMetric(url:id:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMetric"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Deletes the specified metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/deleteMetric(url:id:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/deletemetric(url:id:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/ConversationRecipientController":{"role":"symbol","title":"ConversationRecipientController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRecipientController"}],"abstract":[{"type":"text","text":"Conversation Recipient Business Controller - Singleton accessed via "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ConversationRecipientController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationRecipientController"}],"url":"\/documentation\/headsup_mobile_sdk\/conversationrecipientcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/getMetricByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)":{"role":"symbol","title":"getMetricByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMetricByCalendarRange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calendarRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CalendarRange","preciseIdentifier":"s:18headsup_mobile_sdk13CalendarRangeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entityList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:18headsup_mobile_sdk16MetricControllerC1Txmfp"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets a list of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity"},{"type":"text","text":" objects of the specified type, for a given source and data range"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getMetricByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/getmetricbycalendarrange(url:source:calendarrange:currentdate:scale:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/getUserUnit(unitOfMeasure:)":{"role":"symbol","title":"getUserUnit(unitOfMeasure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserUnit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"unitOfMeasure"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ManualSourceStringValueOptions","preciseIdentifier":"s:18headsup_mobile_sdk30ManualSourceStringValueOptionsC"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Gets the user’s unit of measure from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/ManualSourceStringValueOptions"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getUserUnit(unitOfMeasure:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/getuserunit(unitofmeasure:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/updateMetric(url:id:metricDictionary:completion:)":{"role":"symbol","title":"updateMetric(url:id:metricDictionary:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMetric"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metricDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:18headsup_mobile_sdk16MetricControllerC1Txmfp"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates the specified metric"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/updateMetric(url:id:metricDictionary:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/updatemetric(url:id:metricdictionary:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/TileSettingController":{"role":"symbol","title":"TileSettingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileSettingController"}],"abstract":[{"type":"text","text":"Tile Setting Business Controller - Singleton accessed through the "},{"type":"strong","inlineContent":[{"type":"text","text":"shared"}]},{"type":"text","text":" property"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/TileSettingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileSettingController"}],"url":"\/documentation\/headsup_mobile_sdk\/tilesettingcontroller"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricController/getMetricDictionaryByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)":{"role":"symbol","title":"getMetricDictionaryByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMetricDictionaryByCalendarRange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calendarRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CalendarRange","preciseIdentifier":"s:18headsup_mobile_sdk13CalendarRangeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entityList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?>]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets a dictionary of objects of the specified type for a given source and date range"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricController\/getMetricDictionaryByCalendarRange(url:source:calendarRange:currentDate:scale:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk\/metriccontroller\/getmetricdictionarybycalendarrange(url:source:calendarrange:currentdate:scale:completion:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/MetricEntity":{"role":"symbol","title":"MetricEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetricEntity"}],"abstract":[{"type":"text","text":"Metric Entity"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/MetricEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MetricEntity"}],"url":"\/documentation\/headsup_mobile_sdk\/metricentity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/title","value":"HealthKit"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/fragments","value":[{"kind":"identifier","text":"HealthKit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/title","value":"MetricEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1MetricEntity\/fragments","value":[{"kind":"identifier","text":"MetricEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}