{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHealthKitConnectedOnServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/headsup_mobile_sdk\/healthkit\/ishealthkitconnectedonserver(callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headsup_mobile_sdk\/healthkit\/ishealthkitconnectedonserver(callback:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isHealthKitConnectedOnServer(callback:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHealthKitConnectedOnServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"title":"isHealthKitConnectedOnServer(callback:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@headsup_mobile_sdk@objc(cs)HealthKit(im)isHealthKitConnectedOnServerWithCallback:","modules":[{"name":"headsup_mobile_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"isHealthKitConnectedOnServerWithCallback:"}]},"hierarchy":{"paths":[["doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit"]]},"references":{"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit":{"role":"symbol","title":"HealthKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKit"}],"abstract":[{"type":"text","text":"The primary HealthKit class"}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HealthKit"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk/HealthKit/isHealthKitConnectedOnServer(callback:)":{"role":"symbol","title":"isHealthKitConnectedOnServer(callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHealthKitConnectedOnServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk\/HealthKit\/isHealthKitConnectedOnServer(callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isHealthKitConnectedOnServerWithCallback:"}],"url":"\/documentation\/headsup_mobile_sdk\/healthkit\/ishealthkitconnectedonserver(callback:)"},"doc://com.headsuphealth.headsup-mobile-sdk/documentation/headsup_mobile_sdk":{"role":"collection","title":"headsup_mobile_sdk","abstract":[{"type":"text","text":"This documentation describes how to access the services in the Heads Up Mobile SDK from your own iOS mobile app. The SDK is written in Swift and is available as a Swift Framework."}],"identifier":"doc:\/\/com.headsuphealth.headsup-mobile-sdk\/documentation\/headsup_mobile_sdk","kind":"symbol","type":"topic","url":"\/documentation\/headsup_mobile_sdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isHealthKitConnectedOnServerWithCallback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isHealthKitConnectedOnServerWithCallback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"isHealthKitConnectedOnServerWithCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/title","value":"HealthKit"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit\/fragments","value":[{"kind":"identifier","text":"HealthKit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1isHealthKitConnectedOnServer(callback:)\/title","value":"isHealthKitConnectedOnServerWithCallback:"},{"op":"replace","path":"\/references\/doc:~1~1com.headsuphealth.headsup-mobile-sdk~1documentation~1headsup_mobile_sdk~1HealthKit~1isHealthKitConnectedOnServer(callback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isHealthKitConnectedOnServerWithCallback:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}